### ISSUE TITLE
`shinyDESeq2` error and solution

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [j-andrews7/iBET#8]
Hello @j-andrews7 ,

I followed the README and ran `shinyPCAtools`, `shinyDESeq2`, and` shinyDECorr`.  Both `shinyPCAtools` and `shinyDECorr` showed amazing interactive views and I will try them on my project datasets.  

However, `shinyDESeq2` gave me the following error:
`Error in DESeq2::lfcShrink(dds, coef = coef, lfcThreshold = lfcThreshold) :   coef %in% resultsNamesDDS is not TRUE`

I proceeded as follows and got it running:
```
> resultsNames(dds)
[1] "Intercept"               "cell_N061011_vs_N052611" "cell_N080611_vs_N052611" "cell_N61311_vs_N052611" 
> colData(dds)
> res = results(dds)
> shinyDESeq2(dds, res=res, coef = "dex_trt_vs_untrt", annot.by = c("cell", "dex"))
```
Even though R documentation for `res` says "If not provided, it will be generated from the dds object via lfcShrink or results and coef", but `shinyDESeq2` did not run without that.

I know its a minor issue, just thought of letting you know in case someone else try it. :-)

Thanks.
Gurpreet

**Comment by j-andrews7** [comment]
Ah, it's possible I just haven't updated the README properly after the latest round of updates. Thanks for the tip, I'll check it.

**Comment by j-andrews7** [comment]
Believe this has been fixed.
